# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

orbs:
  android: circleci/android@2.1.2
  gh: circleci/github-cli@1.0

jobs:
  unit-test:
    executor:
      name: android/android-docker
      tag: 2023.02.1
    steps:
      - checkout
      - android/restore-gradle-cache
      - android/run-tests:
          test-command: ./gradlew testDebug
      - android/save-gradle-cache

  android-test:
    executor:
      name: android/android-machine
      tag: 2022.12.1
    steps:
      - checkout
      - android/start-emulator-and-run-tests:
          test-command: ./gradlew connectedAndroidTest
          system-image: system-images;android-30;google_apis;x86

  release-build:
    executor:
      name: android/android-machine
      tag: 2022.12.1
    steps:
      - checkout
      - android/restore-gradle-cache
      - android/restore-build-cache
      - run:
          name: Assemble release build
          command: |
            ./gradlew assembleRelease
      - store_artifacts:
          path: app/build/outputs/apk/release


workflows:
  test-and-build:
    jobs:
      - unit-test:
          filters:
            branches:
              only: develop
      - android-test:
          requires:
            - unit-test
          filters:
            branches:
              only: develop
      - release-build:
          filters:
            branches:
              only: master
      - gh/release:
          tag: 1.0.0
          title: Minnies Installer
          files: ./app/build/outputs/apk/release/app-release.apk
          context:
            - GITHUB_CREDENTIALS
          requires:
            - release-build
          filters:
            branches:
              only: master