# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

orbs:
  android: circleci/android@2.1.2
  gh: circleci/github-cli@1.0

deploy_to_dropbox_premium: &deploy_to_dropbox_premium
  deploy:
    name: Deploy Premium version to DropBox
    command: ./premium_apk_dropbox_deploy.sh

deploy_to_dropbox_free: &deploy_to_dropbox_free
  deploy:
    name: Deploy Free version to DropBox
    command: ./free_apk_dropbox_deploy.sh

fix_permissions: &fix_permissions
  run:
    name: Chmod permissions
    command: sudo chmod +x ./premium_apk_dropbox_deploy.sh

jobs:
  unit-test:
    executor:
      name: android/android-docker
      tag: 2023.02.1
    steps:
      - checkout
      - android/restore-gradle-cache
      - android/run-tests:
          test-command: ./gradlew testPremiumDebug
      - android/save-gradle-cache

  android-test:
    executor:
      name: android/android-machine
      tag: 2022.12.1
    steps:
      - checkout
      - android/start-emulator-and-run-tests:
          test-command: ./gradlew connectedDebugAndroidTest
          system-image: system-images;android-30;google_apis;x86

  release-free-build:
    executor:
      name: android/android-machine
      tag: 2022.12.1
    steps:
      - checkout
      - android/restore-gradle-cache
      - android/restore-build-cache
      - run:
          name: Assemble Free build
          command: |
            ./gradlew assembleFreeRelease
      - store_artifacts:
          path: app/build/outputs/apk/free/release
      - run:
          name: Remove release key
          command: rm ./upload.jks
      - <<: *fix_permissions
      - <<: *deploy_to_dropbox_free

  release-premium-build:
    executor:
      name: android/android-machine
      tag: 2022.12.1
    steps:
      - checkout
      - android/restore-gradle-cache
      - android/restore-build-cache
      - run:
          name: Assemble Premium build
          command: |
            ./gradlew assemblePremiumRelease
      - store_artifacts:
          path: app/build/outputs/apk/premium/release
      - run:
          name: Remove release key
          command: rm ./upload.jks
      - <<: *fix_permissions
      - <<: *deploy_to_dropbox_premium


workflows:
  test-and-build:
    jobs:
      - unit-test:
          filters:
            branches:
              only: develop
      - android-test:
          requires:
            - unit-test
          filters:
            branches:
              only: develop
      - release-free-build:
          filters:
            branches:
              only: master
      - release-premium-build:
          filters:
            branches:
              only: master