package com.demo.minnies.shared.utils

const val PREFERENCE_INITIALIZATION_VECTOR_KEY = "PREFERENCE_INITIALIZATION_VECTOR_KEY"
const val PREFERENCE_SECRET_KEY_KEY = "PREFERENCE_SECRET_KEY_KEY"

const val PREFERENCE_DATASTORE_FILE_NAME = "PREFERENCE_DATASTORE_FILE_NAME"
const val TEST_PREFERENCE_DATASTORE_FILE_NAME = "TEST_PREFERENCE_DATASTORE_FILE_NAME"
const val PROTO_DATASTORE_FILE_NAME = "PROTO_DATASTORE_FILE_NAME"
const val TEST_PROTO_DATASTORE_FILE_NAME = "TEST_PROTO_DATASTORE_FILE_NAME"